# Generated by Django 5.0.3 on 2024-03-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApptuColegio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='colegio',
        ),
        migrations.RemoveField(
            model_name='asignaturas',
            name='colegio',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='promedio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='examenes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
