# Generated by Django 5.0.3 on 2024-03-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApptuColegio', '0002_remove_alumnos_colegio_remove_asignaturas_colegio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaturas',
            name='cargaHoraria',
            field=models.IntegerField(verbose_name='Carga Horaria'),
        ),
        migrations.AlterField(
            model_name='colegios',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
