# Generated by Django 5.0.3 on 2024-03-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApptuColegio', '0003_alter_asignaturas_cargahoraria_alter_colegios_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaturas',
            name='cargaHoraria',
            field=models.IntegerField(),
        ),
    ]
